### ISSUE TITLE
Add utils subpackage folder

### ISSUE THREAD

**Issue by abhi8893** [abhi8893/simplecarboncleaner#1]
We need to add a utils subpackage. This will primarily include general utilities which can be used to build up specialized functionalities for cleaning/processing carbon records:

IDEAS: 
- Text cleaning routines
- Good abstractions over pandas functionality
- General functionalities

Right now we just need a simple structure for this issue.

**Comment by anu-coder** [comment]
I have created a subpackage `utils` with the following structure:
```
 utils
    ├───generic
    ├───io
    ├───patches
    └───text
```

**Comment by abhi8893** [comment]
Yeah, seems nice. We can focus on the development of such individual modules. Just to be sure, `generic`, `io`, `patches`, `text` are all `.py` files i.e. modules, right? And **NOT** subpackages?

**Comment by anu-coder** [comment]
Yes, I have created modules and not subpackages, so all of them are `.py` files
